name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --force

      - name: Build static files
        run: npm run build

      - name: Compress build
        run: tar -czf out.tar.gz out/

      - name: Upload built files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "out.tar.gz"
          target: "/opt/urbantransitmap/frontend-deploy/releases/"

      - name: Deploy frontend on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /opt/urbantransitmap/frontend-deploy/deploy_frontend.sh
